config/routes.rb
Rails.application.routes.draw do
  resources :articles, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout -> { (turbo_frame_request? && !turbo_stream_request?) ? false : "application" }

  private

  def turbo_stream_request?
    request.accept.starts_with?(Mime[:turbo_stream])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      respond_to do |format|
        format.html { redirect_to articles_path, notice: "Article was successfully created." }
        format.turbo_stream { flash.now[:notice] = "Article was successfully created." }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def article_params
    params.require(:article).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_article.html.erb
<div>
  Article #<%= article.id %>: <%= article.content %>
</div>

app/views/articles/_form.html.erb
<%= form_with model: article do |f| %>
  <%= f.label :content %>
  <%= f.text_field :content %>

  <%= f.submit %>
<% end %>

app/views/articles/create.turbo_stream.erb
<%= turbo_stream.update "new_article", "" %>
<%= turbo_stream.append "articles", @article %>

app/views/articles/index.html.erb
<h1>Articles</h1>

<%= link_to "New article", new_article_path, data: { turbo_frame: "new_article" } %>

<%= turbo_frame_tag "new_article" %>

<div id="articles">
  <%= render @articles %>
</div>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= link_to "Back to articles", articles_path %>

<%= turbo_frame_tag "new_article" do %>
  <%= render "form", article: @article %>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <div>
    <%= message %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LayoutReproduction</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div id="flash">
      <%= render "layouts/flash" %>
    </div>

    <%= yield %>
  </body>
</html>

app/views/layouts/application.turbo_stream.erb
<%= turbo_stream.update "flash", partial: "layouts/flash" %>

<%= yield %>